# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
   # pre = "<i class=\"fa fa-info-circle\"></i>"
    name = "Description"
    url = "/description/"
    weight = 10
    
[[main]]
    name = "Schedule"
 #    pre = "<i class=\"fa fa-calendar\" aria-hidden=\"true\"></i>"
    url = "/schedule/"
    weight = 20

[[main]]
   # pre = "<i class=\"fa fa-info-circle\"></i>"
    name = "Project"
    url = "/project/"
    weight = 30

    
[[main]]
    url = "https://github.com/StatMix"
    name  = "<i class='fab fa-github fa-lg'></i>"
    weight = 80
    





