<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Stats Team">

<title>gWQS Model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="WQS_Tutorial_files/libs/clipboard/clipboard.min.js"></script>
<script src="WQS_Tutorial_files/libs/quarto-html/quarto.js"></script>
<script src="WQS_Tutorial_files/libs/quarto-html/popper.min.js"></script>
<script src="WQS_Tutorial_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="WQS_Tutorial_files/libs/quarto-html/anchor.min.js"></script>
<link href="WQS_Tutorial_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="WQS_Tutorial_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="WQS_Tutorial_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="WQS_Tutorial_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="WQS_Tutorial_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">gWQS Model</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Tutorial 2</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Stats Team </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<section id="weighted-quantile-sum-regression" class="level1" style="color:#6495ED">
<h1>Weighted Quantile Sum Regression</h1>
</section>
<p>Assume we are interested in exploring the relationship between the chemical exposures and the outcome (BMI for example). These chemical exposures are usually highly correlated with each other (known as multicolinearity phenonmenon in regression). Multicolinearity among the exposures violates the independence model assumption of multivariate linear regression, distorting statistical inference. To eliminate the issue of multicolinearity, we can consider summarizing these highly correlated chemical mixtures when putting them into a regression model. The idea of summary motivates the weighted quantile sum regression.</p>
<p>Unlike multivariate regression, the WQS model uses quantiles and weights each chemical exposures variable based on its individual impact on the overall outcome. The exposures in the model that have a strong impact on the mixture are assigned a greater weight while others that are not as critical are given a lower weight. To test the calculated weights and verify that the model is sufficient, the WQS package in R tests these weights to ensure the model is sufficient.</p>
<section id="libraries" class="level2" style="color:#6495ED">
<h2 class="anchored" data-anchor-id="libraries">Libraries</h2>
</section>
<p>In order to investigate relationships between chemical exposures using the gWQS package, there are several packages in R that must be loaded. Similar to previous tutorials where packages were introduced, we will be using tidyverse and tidymodels, but we will also use ggcorrplot and gWQS.</p>
<p>In order to use the new packages in this tutorial, they must first be installed in R by running the following lines of code <code>install.packages("ggcorrplot")</code> and <code>install.packages("gWQS")</code>in the console.</p>
<div class="callout-warning callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Additional installations may be required for mac users!</p>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gWQS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome to Weighted Quantile Sum (WQS) Regression.
If you are using a Mac you have to install XQuartz.
You can download it from: https://www.xquartz.org/</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages
───────────────────────────────────────
tidyverse 1.3.2 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ ggplot2 3.4.0      ✔ purrr   1.0.0 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.5.0 
✔ readr   2.1.2      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.0.0 ──
✔ broom        1.0.1     ✔ rsample      1.1.1
✔ dials        1.1.0     ✔ tune         1.0.1
✔ infer        1.0.4     ✔ workflows    1.1.2
✔ modeldata    1.0.1     ✔ workflowsets 1.0.0
✔ parsnip      1.0.3     ✔ yardstick    1.1.0
✔ recipes      1.0.3     
── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Use suppressPackageStartupMessages() to eliminate package startup messages</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggcorrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this tutorial, we use the new base R pipe operator “|&gt;” which is equivalent to “%&gt;%”</p>
</div>
</div>
<section id="exploratory-data-analysis" class="level2" style="color:#6495ED">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
</section>
<p>As discussed early, we want to apply Weighted Quantile Sums to a real world issue. This example uses the NHANES dataset to focuses on specific chemical exposures: Phalates and Phytoestrogens. Both of these exposures can be detected in urine samples and we want to estimate their respective impact on the outcome, body mass index. In order to predict body mass index with urine samples, we first need to reintroduce the NHANES dataset for use in this example.</p>
<p>The NHANES dataset can be loaded into R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="at">file=</span><span class="st">'nhanes1518.rda'</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nhanes1518)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 52
   SEQN WTINT2YR WTMEC…¹ RIDST…² RIAGE…³ RIDAG…⁴ INDFM…⁵ RIDRE…⁶ DMDED…⁷ DMDED…⁸
  &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;int&gt;   &lt;int&gt;   &lt;int&gt;   &lt;dbl&gt;   &lt;int&gt;   &lt;int&gt;   &lt;int&gt;
1 83732  134671. 135630.       2       1      62    4.39       3       5      NA
2 83733   24329.  25282.       2       1      53    1.32       3       3      NA
3 83734   12400.  12576.       2       1      78    1.51       3       3      NA
4 83735  102718. 102079.       2       2      56    5          3       5      NA
5 83736   17628.  18235.       2       2      42    1.23       4       4      NA
6 83737   11252.  10879.       2       2      72    2.82       1       2      NA
# … with 42 more variables: INDHHIN2 &lt;int&gt;, BMXBMI &lt;dbl&gt;, BMXWAIST &lt;dbl&gt;,
#   BMXWT &lt;dbl&gt;, BMXHT &lt;dbl&gt;, URXUCR &lt;dbl&gt;, WTSB2YR &lt;dbl&gt;, URXCNP &lt;dbl&gt;,
#   URDCNPLC &lt;int&gt;, URXCOP &lt;dbl&gt;, URDCOPLC &lt;int&gt;, URXECP &lt;dbl&gt;, URDECPLC &lt;int&gt;,
#   URXHIBP &lt;dbl&gt;, URDHIBLC &lt;int&gt;, URXMBP &lt;dbl&gt;, URDMBPLC &lt;int&gt;, URXMC1 &lt;dbl&gt;,
#   URDMC1LC &lt;int&gt;, URXMCOH &lt;dbl&gt;, URDMCOLC &lt;int&gt;, URXMEP &lt;dbl&gt;,
#   URDMEPLC &lt;int&gt;, URXMHBP &lt;dbl&gt;, URDMHBLC &lt;int&gt;, URXMHH &lt;dbl&gt;,
#   URDMHHLC &lt;int&gt;, URXMHNC &lt;dbl&gt;, URDMCHLC &lt;int&gt;, URXMHP &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>Once the data is loaded, we can proceed to understand how our chemical exposures (detected in urine samples) impact the bodymass index of participants.</p>
<p>Similar to the previous tutorial where age is filtered, we only want to consider participants in the data that are above 18 years old and take the natural log of BMI. By filtering and using the natural log, the distribution of the ages of participants are normalized. To finish preparing the dataset, the N/A values are removed and the resulting data is saved under the name <code>nhanes</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>nhanes <span class="ot">&lt;-</span> nhanes1518 <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(RIDAGEYR<span class="sc">&gt;=</span><span class="dv">18</span>)<span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">BMXBMI =</span> <span class="fu">log</span>(BMXBMI))<span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(BMXBMI, URXMHBP, URXMOH, URXMHP, URXMHH, URXMCOH, URXMHNC, URXMHH, URXECP, URXHIBP, URXMIB)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>nhanes <span class="ot">&lt;-</span> <span class="fu">drop_na</span>(nhanes)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>nhanes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,523 × 10
   BMXBMI URXMHBP URXMOH URXMHP URXMHH URXMCOH URXMHNC URXECP URXHIBP URXMIB
    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
 1   3.01    5.3     7.8   2       8.7    0.7     1.2    14.1    27.4   73.7
 2   3.18    0.5     8.6   3.1    11.9    0.35    0.28   16.7     1.5    4.4
 3   3.78    1.1     8.4   0.57   16.4    0.6     0.28   25.8     6.3   32.7
 4   3.64    1.5     7.8   1.2    14.4    0.6     1.1    19.7     4.7    8.8
 5   3.27    0.5     1.7   0.57    2.7    0.6     0.9     3.9     2      7.1
 6   3.22    1.9    15.4   8.2    27.6    0.35    0.5    26.1     6.1   13.4
 7   3.13    0.28    6     5.1     9.5   14.2    72.2    14.1     3.7   17  
 8   3.53    1.8     1.9   2.1     2.7    0.35    0.4     4       4.9   14.7
 9   3.43    1.5     5     2.6     6.2    0.35    0.28    9.4     1.4    3.7
10   3.53    0.28    2.6   0.57    5.1    0.9     0.8     5.9     3.2   12.8
# … with 3,513 more rows</code></pre>
</div>
</div>
<p>To confirm the normality of the variable BMI, we can create a histogram to view the shape of the observations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a> nhanes<span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> BMXBMI))<span class="sc">+</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_histogram</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="WQS_Tutorial_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="key-assumptionsconstraints" class="level2" style="color:#6495ED">
<h2 class="anchored" data-anchor-id="key-assumptionsconstraints">Key Assumptions/Constraints</h2>
</section>
<p>In order to use the gWQS package in an application setting, several conditions must be followed. The first condition is that the chemical exposures must ALL contribute in one direction. In order to contribute in one direction, all variables must be either positively correlated, or negatively correlated with each other. In addition to the correlation of the exposures, the dataset must be split into two sections. The first section is the training data for providing weights to the variables, while the second is used exclusively for verifying the model and ensuring that the results are reliable.</p>
<p><strong><em>In order to use weighted quantile sum regression with the <code>nhanes</code> data, it is important to first confirm that all constraints are satisfied:</em></strong></p>
<p><strong><em>An initial correlation model reveals that the URX predictor variables all contribute in a single direction, validating the appropriateness of the gWQS model.</em></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>cor_hanes <span class="ot">&lt;-</span> <span class="fu">cor</span>(nhanes)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorrplot</span>(cor_hanes)<span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Corrleation of URX Variables and BMI"</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WQS_Tutorial_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Source http://www.sthda.com/english/wiki/ggcorrplot-visualization-of-a-correlation-matrix-using-ggplot2#:~:text=The%20easiest%20way%20to%20visualize,ggcorr()%20in%20ggally%20package</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>However, if we fit a normal linear regression model to these predictors, positive and negative estimates would be produced. Intuitively, the URX variables should all have positive coefficients, however, this model is not representative of this assumption. This is a demonstration of multi-collinearity, where there are there is a large uncertainty (variance) when calculating the coefficients. Therefore, the output of the model may produce unusual signs for the beta estimates.</p>
<p>As shown below, some of the URX betas are positive, while others are negative. Instead, we want to use a gWQS model which will provide a <strong><em>unidirectional</em></strong> output, similar to a standard linear regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#large uncertanty (variance) around the coefficients and multicolinearity (including that the coeffients may be negatve) - point estimate may be negative (abnormal signs)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">linear_reg</span>()<span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(BMXBMI<span class="sc">~</span>., <span class="at">data =</span> nhanes)<span class="sc">|&gt;</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 5
   term          estimate std.error statistic   p.value
   &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept)  3.36       0.00509   660.     0        
 2 URXMHBP     -0.0000177  0.000839   -0.0211 0.983    
 3 URXMOH       0.00209    0.00174     1.21   0.228    
 4 URXMHP      -0.00704    0.00164    -4.29   0.0000182
 5 URXMHH       0.000405   0.00101     0.401  0.688    
 6 URXMCOH      0.00238    0.00105     2.26   0.0236   
 7 URXMHNC     -0.000869   0.000402   -2.16   0.0306   
 8 URXECP      -0.0000514  0.000285   -0.180  0.857    
 9 URXHIBP     -0.00567    0.00155    -3.67   0.000250 
10 URXMIB       0.00185    0.000464    3.98   0.0000693</code></pre>
</div>
</div>
<p>Once the conditions are satisfied, a model can be produced, similarly to standard linear regression model. One difference from the linear model is that unique weights are assigned to the predictor variables.</p>
<p><span class="math display">\[
g(\mu)= \beta_0 + \beta_0  \times (WQS) + \epsilon
\]</span></p>
<p>Quantiles categorize each variable where qi = {0, 1, 2, 3, etc.}, which are given a corresponding weight. The weighted components are then summed and are fitted to the regression model. gWQS visualizes the assigned weights and regression fit as demonstrated in the package below:</p>
<section id="using-gwqs-package" class="level2" style="color:#6495ED">
<h2 class="anchored" data-anchor-id="using-gwqs-package">Using gWQS Package</h2>
</section>
<p>The gWQS model model requires the explanatory mixtures to be saved to a variable. In this example, we saved them to <code>chem_names</code>.</p>
<p>Additionally, the output of the gWQS package is saved to the variable <code>results</code>.</p>
<p><strong><em>Key arguments in the qWQS package:</em></strong></p>
<p><code>q</code> - specifies the number of quantiles to be used</p>
<p><code>validation</code> - the percentage of the data set to be used for creating the weights/bootstrapping and the validating the model</p>
<p><code>b1_pos</code> - specify <code>TRUE</code> if the data has a positive correlation and</p>
<p><code>FALSE</code> if it has a negative correlation</p>
<p><code>family</code> - type of association to be tested (ex: gaussian, binomial)</p>
<p><code>data</code> - the data-frame containing the data to be tested</p>
<p><code>b</code> - number of bootstrap samples</p>
<p><code>mix_name</code> - a vector containing the names of the exposures</p>
<p><code>seed</code> - set a seed which allows the results to be replicated</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>chem_names <span class="ot">&lt;-</span> <span class="fu">names</span>(nhanes)[<span class="dv">2</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">gwqs</span>(BMXBMI <span class="sc">~</span> wqs, <span class="at">mix_name =</span> chem_names, <span class="at">data =</span> nhanes, </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">q =</span> <span class="dv">10</span>, <span class="at">validation =</span> <span class="fl">0.6</span>, <span class="at">b =</span> <span class="dv">1</span>, <span class="at">b1_pos =</span> <span class="cn">TRUE</span>, </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">b1_constr =</span> <span class="cn">FALSE</span>, <span class="at">family =</span> <span class="st">"gaussian"</span>, <span class="at">seed=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-warning callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>It is important to set a seed in the gWQS model. This ensures that the results are replicated consistently when the model is rendered.</p>
</div>
</div>
</div>
<section id="model-diagnostics-interpretation" class="level2" style="color:#6495ED">
<h2 class="anchored" data-anchor-id="model-diagnostics-interpretation">Model Diagnostics &amp; Interpretation</h2>
</section>
<p>Once we have completed the model, the gWQS package provides methods for understanding and visualizing the results. One of the most helpful ways to view the output of is through visualizations of the weights assigned to each variable. The weights can demonstrate which exposures from the urine samples are impactful in predicting BMI and which are less helpful.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gwqs_barplot</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WQS_Tutorial_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The first visualization produced is a bar plot showing the weights assigned to each of the URX variables. The variables with greatest weights are URXCEP, URXMOH, and URHMIB while the remaining chemicals are not great predictors of BMI. Also shown in the visualization is a red line which shows the cutoff values - calculated by the inverse of the number of predictor variables.</p>
<p>In addition to the weights assigned to the chemical exposures, it can be helpful to visualize the overall relationship of the WQS model and the predicted BMI. To visualize this relationship, a scatterplot can be utilized to see if there is a linear relationship in the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gwqs_scatterplot</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="WQS_Tutorial_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The scatterplot of the WQS model and BMI demonstrate the linear relationship between the URX chemicals and log BMI.</p>
<p>An additional method of verifying that the WQS model is effective in predicting log BMI is to examine the residuals. Residuals are the differences between the the actual data points in the NHANES dataset and the predicted values from our gWQS model. By examining the residuals on a graph, we can determine if there are any relationships, causing issues with the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gwqs_fitted_vs_resid</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="WQS_Tutorial_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The final visualization shows the residuals and fitted values. As seen above, the points are distributed around zero and do not have any distinct patterns. Additional interpretations of the output models can be found HERE (link to Olivia’s tutorial)</p>
<p>Additionally, the final weights are shown numerically below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(results<span class="sc">$</span>final_weights)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        mix_name  mean_weight
URXECP    URXECP 4.635526e-01
URXMCOH  URXMCOH 4.231238e-01
URXMIB    URXMIB 1.133201e-01
URXMHH    URXMHH 1.766439e-06
URXMOH    URXMOH 1.535145e-06
URXMHNC  URXMHNC 1.131088e-07</code></pre>
</div>
</div>
<p>Using these weights, the final regression results can be obtained:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
gwqs(formula = BMXBMI ~ wqs, data = nhanes, mix_name = chem_names, 
    b = 1, b1_pos = TRUE, b1_constr = FALSE, q = 10, validation = 0.6, 
    family = "gaussian", seed = 1)

Deviance Residuals: 
     Min        1Q    Median        3Q       Max  
-0.57623  -0.16121  -0.01061   0.14323   0.95830  

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 3.318215   0.009803 338.499  &lt; 2e-16 ***
wqs         0.014915   0.002861   5.214 2.03e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.05406224)

    Null deviance: 115.65  on 2113  degrees of freedom
Residual deviance: 114.18  on 2112  degrees of freedom
AIC: -164.58

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>The Regression output:</p>
<p><span class="math display">\[
\widehat{log(BMXBMI)} = 3.31 + 0.015 \times (WQS)
\]</span></p>
<p>Interpretation for the model:</p>
<ul>
<li><p><em>When quantiles of the URX variables are 0, the estimated log BMI is approximately 3.31.</em></p></li>
<li><p><em>As every quantile of the WQS increases by 1, the log BMI increases on average by 0.015.</em></p></li>
</ul>
<p>Included in the regression output is the results significance tests of the coefficients. To test the significance of the model, we can use a t-distribution and t-statistic. The t-statistic for WQS is 5.214 under the t-distribution with 7 degrees of freedom. The p-value corresponding to the WQS quantiles is extremely small, therefore, there is a significant relationship between the weighted quantiles and the predicted outcome, logBMI.</p>
<p>Another method of testing the significance of the regression model is using a Chi-Square test. In general, chi-square tests help us determine if there is a difference between the data of the predicted and actual outcome. In this example, it is appropriate to determine if the produced WQS model was due to random chance, or if there is a true relationship present.</p>
<p>To complete the chi-square test, we need to convert the statistic of 1.4 with 1 degree of freedom to a standard p-value. When we find the p-value by using the following formula:</p>
<p><code>anova(model_name, test="Chisq")</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#anova(model, test="Chisq")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Although the model is significant, it is important to acknowledge the uncertainty in the WQS output. One method of accounting for this uncertainty is through confidence intervals.A confidence interval allows us to understand between which values are the estimations from our model likely to occur in the real-world, accounting for model variaitions. Using the <code>confint(model name)</code> function in R, we can determine between which WQS coefficient by the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %     97.5 %
(Intercept) 3.299001588 3.33742763
wqs         0.009308286 0.02052193</code></pre>
</div>
</div>
<p>We can be 95% confident that the true wqs coefficient falls within the interval 27.75 and 28.96.</p>
<section id="model-evaluation" class="level2" style="color:#6495ED">
<h2 class="anchored" data-anchor-id="model-evaluation">Model Evaluation:</h2>
</section>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  gwqs(formula = BMXBMI ~ wqs, data = nhanes, mix_name = chem_names, 
    b = 1, b1_pos = TRUE, b1_constr = FALSE, q = 10, validation = 0.6, 
    family = "gaussian", seed = 1)

Coefficients:
(Intercept)          wqs  
    3.31821      0.01492  

Degrees of Freedom: 2113 Total (i.e. Null);  2112 Residual
Null Deviance:      115.6 
Residual Deviance: 114.2    AIC: -164.6</code></pre>
</div>
</div>
<ul>
<li><p>AIC - This is a statistic to compare two models - the smaller the AIC, the better the model. In this example, the AIC is -164.58.</p></li>
<li><p>Dispersion parameter for gaussian family taken to be 0.05409048, which corresponds to the spread of the data around zero.</p></li>
</ul>
<p>Null deviance can show how well the model predicts the response, solely using the regression intercept.</p>
<p>Contrary, residual deviance demonstrates how well the model predicts the response, using the explanatory variables. The smaller the residual deviance, the better the accuracy of the regression model.</p>
<p>Another measure of validating our model is to examine the residual plot. As demonstrated above, the residuals do not have a general pattern and seem to be evenly distributed near zero.</p>
<p><strong><em>Additional outputs from the model which may be helpful for diagnostics:</em></strong></p>
<p><code>results$bres</code> - displays the p-values for each of the bootstrap samples</p>
<p><code>results$q_i</code> - the “cutoff” values which are used to create the quantiles</p>
<p>In conclusion, the gWQS weighted the explanatory variables successfully as our model is considered to be statistically significant. By using the gWQS model with data where explanatory variables are all highly correlated, specific variables can be weighted according to their influence to the response variable. In the NHANES data set, chemicals URXMCOH, URXMIB, URXECP were weighted the highest by the gWQS model. In future tutorials, we will uncover additional methods to test highly correlated data through Bayesian sum regression.</p>
<section id="acknowledgements" class="level2" style="color:#6495ED">
<h2 class="anchored" data-anchor-id="acknowledgements">Acknowledgements:</h2>
</section>
<ul>
<li><p>https://www.statology.org/null-residual-deviance/#:~:text=The%20residual%20deviance%20tells%20us,value%20of%20the%20response%20variable</p></li>
<li><p>https://cran.r-project.org/web/packages/gWQS/vignettes/gwqs-vignette.html</p></li>
<li><p>http://cran.nexr.com/web/packages/gWQS/vignettes/gwqs-vignette.html</p></li>
<li><p>http://cran.nexr.com/web/packages/gWQS/gWQS.pdf</p></li>
</ul>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>